import React,{ Component,PropTypes } from 'react'
import { connet } from 'react-redux'
import { addTodo,completeTodo,setVisibilityFilter,VisibilityFilters } from '../reducers/actions'
import AddTodo from '../components/AddTodo'
import TodoList from '../components/TodoList'